### PR TITLE
Solved Issue #22

### PR DESCRIPTION
**Pull request by asryan11**
[Build Array from Permutation](https://leetcode.com/problems/build-array-from-permutation/)
Solved the above question in Python.

### CODE REVIEW

**Comment by Vishwas2** [comment]
Please read CONTRIBUTING.md to understand how to contribute to this repo. You can only solve questions in Java.

**Comment by asryan11** [comment]
Ohh, okay my bad.

**Comment by Vishwas2** [comment]
> Ohh, okay my bad.

No problem 😁. Please let me know if you know Java or not. I will close this PR and assign it to someone else if you are not able to do it.

**Comment by asryan11** [comment]
You can assign this issue to someone else.

**Pull request closed without merging**
