### PR TITLE
Sort_Color

### PR DESCRIPTION
**Pull request by Ydvaaman**
@vishwas2 please review my PR of issue https://github.com/Vishwas2/Hacktoberfest2023/issues/76

### CODE REVIEW

**Comment by Vishwas2** [comment]
Please write the question before the solution to make it easier for the reader to understand

**Comment by Ydvaaman** [comment]
ok, sure

**Comment by Ydvaaman** [comment]
@Vishwas2 pls review it now

**Comment by Vishwas2** [comment]
Good job @Ydvaaman. Thank you for contributing to this repo😁.

**Pull request merged**
