### PR TITLE
Create ReverseInteger.java

### PR DESCRIPTION
**Pull request by Pakeetharan**
Issue: #5 
Description: Solution for Leetcode Problem - Reverse Integer

### CODE REVIEW

**Comment by Vishwas2** [comment]
@Pakeetharan please write the question before the solution to make it easier for the reader to understand.

**Comment by Pakeetharan** [comment]
@Vishwas2 Added to a new commit and updated

**Comment by Vishwas2** [comment]
Good work @Pakeetharan , just add an underscore between Reverse and Integer (rename the file to Reverse_Integer) and I will merge it. :)

**Comment by Pakeetharan** [comment]
@Vishwas2 done

**Pull request merged**
