### PR TITLE
Create Flood _fill_algoritim

### PR DESCRIPTION
**Pull request by Divyansh200102**
#70

### CODE REVIEW

**Comment by Vishwas2** [comment]
Please write the question before the solution to make it easier for the reader to understand.

**Comment by Divyansh200102** [comment]
> Please write the question before the solution to make it easier for the reader to und

**Comment by Divyansh200102** [comment]
> Please write the question before the solution to make it easier for the reader to understand.

okay

**Comment by Divyansh200102** [comment]
> > Please write the question before the solution to make it easier for the reader to und

please check it now @Vishwas2

**Comment by Vishwas2** [comment]
This issue has already been solved

**Pull request closed without merging**
